[package]
name = "tari-cc-private-ballot-verifier"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
tari-cc-private-ballot-ballot = { path = "../ballot" }
tari-cc-private-ballot-crypto = { path = "../crypto" }
tari-cc-private-ballot-protocol = { path = "../protocol" }
tari-cc-private-ballot-registry = { path = "../registry" }

[dev-dependencies]
tari-cc-private-ballot-crypto = { path = "../crypto", features = ["test-only-suites"] }

[lints]
workspace = true
